# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1efd771325d8ede5bcbbf5ee55fb6524782770030c4d84f607d3ec9cda3a14b0c4c47a50666faea4329fb1a03a03eac4aa92cc441cc135ac26b65ee0a46e9ce1

test:
  secret_key_base: 0fd7815cc79adc9d498d309101f047ccfc40a49d5afb0f96536dd91e4a792952493757a1fc8f45a15367c8e95f24aebfc42f77887ac405af9846b4d114bfc089

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
